services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter_lab
    image: mle_assignment2_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--notebook-dir=/app", "--IdentityProvider.token="]

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: mle_assignment2_airflow
    container_name: airflow_init 
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./datamart:/app/datamart
      - ./data:/app/data
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

  airflow-webserver:
    image: mle_assignment2_airflow
    container_name: airflow_webserver
    user: root  
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./datamart:/app/datamart
      - ./data:/app/data
      - ./models:/app/models
      - ./predictions:/app/predictions
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    image: mle_assignment2_airflow
    container_name: airflow_scheduler
    user: root 
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./datamart:/app/datamart
      - ./data:/app/data
      - ./models:/app/models
      - ./predictions:/app/predictions
    command: airflow scheduler

volumes:
  airflow_data:
